### ISSUE TITLE
Thoughts on line highlight?

### ISSUE THREAD

**Issue by aarongustafson** [ericwbailey/a11y-syntax-highlighting#2]
I don’t think I saw it covered in the Prism instance.

**Comment by ericwbailey** [comment]
Love the idea. I'll see what I can do!

**Comment by aarongustafson** [comment]
Thank you!

**Comment by ericwbailey** [comment]
@aarongustafson I was wondering if I could get your opinion. Prism uses an absolutely positioned stripe to draw the highlight effect. This means that it sits on top of the underlying code content.

The highlight effect comes from a semitransparent background color, which is transparent enough to let someone see the underlying content. The problem is a treatment that is transparent enough to see code is also faint enough that it would fail color contrast, meaning a person may not know the highlight is present. Making it more opaque means that the opposite happens, the code becomes not high enough contrast.

To get around this, I was playing with a border treatment to indicate the highlight bounds. What do you think of something like this?

<img width="905" alt="Sample HTML code, where one line is highlighted with a top and bottom border." src="https://user-images.githubusercontent.com/634191/132786353-7ce6b482-5d9d-4620-bdd7-47a3a991a3be.png">

I had a darker color palette for the class tokens worked out, but I can't crack how to get child elements to pop out from underneath something absolutely positioned like this.

**Comment by aarongustafson** [comment]
It’s a challenge for sure. I don’t dislike the borders, but I’m curious: could you apply a `backdrop-filter` to either invert or hue-rotate the highlight? Normally I’d shy away from [a feature that only has ~70% support globally](https://caniuse.com/css-backdrop-filter), but given that code samples are more likely to be viewed by folks on a more modern browser (except Firefox), maybe it’s ok? Or maybe one with the other as a fallback (upgraded via `@supports`)?

**Comment by ericwbailey** [comment]
Oh, I _love_ that idea. Will play around a bit with it this weekend, thank you!

**Comment by ericwbailey** [comment]
So, the good news is that `backdrop-filter` cracks the child element issue. The bad news is the color contrast algorithm won't honor just a 180° flip for inversion or rotation. Dark type on light is ranked differently, so adjustments that get one color working may cause others to fail.

Because of that I'm going to take the border approach, at least until something like `:has()` becomes available.

**Comment by aarongustafson** [comment]
Ah, that's a shame. Did you try hue rotation at all?

**Comment by ericwbailey** [comment]
Yeah. I couldn't find a value that would satisfy everything, unfortunately.

**Comment by aarongustafson** [comment]
Bummer. Oh well, borders it is.

**Comment by ericwbailey** [comment]
Just added support! Thank you again for suggesting it.
